export const SELECTED_FORM_FIELD = 'SELECTED_FORM_FIELD';
export const SET_LAYOUT = 'SET_LAYOUTS';
export const SET_INITIAL_LAYOUT = 'SET_INITIAL_LAYOUTS';

export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
