import shortid from 'shortid';

export const SIDEBAR_ITEM = 'sidebarItem';
export const ROW = 'row';
export const COLUMN = 'column';
export const COMPONENT = 'component';

export const SIDEBAR_ITEMS = [
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'text',
    fieldName: 'Single Line',
    label: 'Single line',
    placeHolder: 'single line',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'text',
    fieldName: 'Multi-Line',
    label: 'Multi line',
    placeHolder: 'multi line',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'number',
    fieldName: 'Number',
    label: 'number',
    placeHolder: 'number',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'number',
    fieldName: 'Decimal',
    label: 'Decimal',
    placeHolder: 'Decimal',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'text',
    fieldName: 'Address',
    label: 'Address',
    placeHolder: 'address',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'number',
    fieldName: 'Phone',
    label: 'Phone',
    placeHolder: 'phone',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'email',
    fieldName: 'Email',
    label: 'Email',
    placeHolder: 'Email',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'date',
    fieldName: 'Date',
    label: 'Date',
    placeHolder: 'date',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },

  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'time',
    fieldName: 'Time',
    label: 'Time',
    placeHolder: 'time',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'datetime-local',
    fieldName: 'Date-Time',
    label: 'Date Time',
    placeHolder: 'date and Time',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'checkbox',
    fieldName: 'Decision Box',
    label: 'Decision Box',
    placeHolder: 'Decision Box',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'select',
    isMultiSelect: false,
    fieldName: 'Dropdown',
    label: 'Dropdown',
    placeHolder: 'Dropdown',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'radio',
    fieldName: 'Radio',
    label: 'Radio',
    placeHolder: 'Radio',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },

  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'select',
    isMultiSelect: true,
    fieldName: 'Multiple choice',
    label: 'Multiple choice',
    placeHolder: 'Multiple choice',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'checkbox',
    fieldName: 'Checkbox',
    label: 'Checkbox',
    placeHolder: 'Checkbox',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'url',
    isMultiSelect: true,
    fieldName: 'Website',
    label: 'Website',
    placeHolder: 'Website',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'number',
    fieldName: 'Currency',
    label: 'Currency',
    placeHolder: 'Currency',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'file',
    isImageOnly: false,
    fieldName: 'File Upload',
    label: 'File Upload',
    placeHolder: 'File Upload',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'file',
    isImageOnly: true,
    fieldName: 'Image Upload',
    label: 'Image Upload',
    placeHolder: 'Image Upload',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'text',
    fieldName: 'Section',
    label: 'Section',
    placeHolder: 'Section',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'rich text editor',
    fieldName: 'Description',
    label: 'Description',
    placeHolder: 'Description',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'range',
    fieldName: 'Slider',
    label: 'Slider',
    placeHolder: 'Slider',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'ratings',
    fieldName: 'Ratings',
    label: 'Ratings',
    placeHolder: 'Ratings',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'google address',
    fieldName: 'Google Address Field',
    label: 'Google Address Field',
    placeHolder: 'Google Address Field',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'checkbox',
    fieldName: 'Terms and Conditions',
    label: 'Terms and Conditions',
    placeHolder: 'Terms and Conditions',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
  {
    id: shortid.generate(),
    type: SIDEBAR_ITEM,
    srNo: 0,
    inputType: 'text',
    fieldName: 'Signature',
    label: 'Signature',
    placeHolder: 'Signature',
    default: '',
    name: '',
    inputId: '',
    allowedRoles: [],
    validations: [],
  },
];


// page break, unique ID not added